### ISSUE TITLE
ArrayIndexOutOfBoundsException on re-signing

### ISSUE THREAD

**Issue by ebourg** [ebourg/jsign#2]
Issue reported by @mlocati in the Issue #1:

I encountered an unhanded exception while signing an executable (let's call it /path/to/filename.exe).
This executable was initially signed, then altered (it's an sfx and I added files to it). Resigning it caused the following error to be thrown:

```
java failed: Adding Authenticode signature to /path/to/filename.exe
Couldn't sign /path/to/filename.exe
java.lang.ArrayIndexOutOfBoundsException
at sun.security.provider.DigestBase.engineUpdate(DigestBase.java:118)
at java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:555)
at java.security.MessageDigest.update(MessageDigest.java:300)
at net.jsign.pe.PEFile.computeDigest(PEFile.java:695)
at net.jsign.pe.PEFile.computeDigest(PEFile.java:707)
at net.jsign.PESigner.createSignature(PESigner.java:189)
at net.jsign.PESigner.createCertificateTable(PESigner.java:157)
at net.jsign.PESigner.sign(PESigner.java:150)
at net.jsign.PESignerCLI.execute(PESignerCLI.java:223)
at net.jsign.PESignerCLI.main(PESignerCLI.java:48)
```

**Comment by ebourg** [comment]
@mlocati  This should be fixed by d373eb830a6fda604b99d35a3df90cff58fb2619.
