### ISSUE TITLE
Unsupported File ".exe"

### ISSUE THREAD

**Issue by isagargit** [ebourg/jsign#212]
We are using GaraSign CLI to sign .NET packages that internally uses jsign. I have installed jsign 6.0 but when i try to sign a .exe file i get the error:

[2024-03-22T05:57:54Z] - INFO | == Begin jsign output ==
[2024-03-22T05:57:54Z] - INFO | jsign: Unsupported file: testapp.exe
[2024-03-22T05:57:54Z] - INFO | Try `jsign --help' for more information.

DLL signing works perfectly

**Comment by ebourg** [comment]
It looks like Jsign fails to parse the .exe file, are you sure the file is valid? If you can send the file to ebourg@apache.org I'll give it a look.

**Comment by isagargit** [comment]
The file is valid, but actually cant share it. can you still suggest what could be wrong. jsign should work right ?

**Comment by ebourg** [comment]
Could you share at least the header of the file? The first 1K will be enough to analyze the issue.

**Comment by isagargit** [comment]
I parsed the file using pefile module. Here's the file
[pefile_output.txt](https://github.com/ebourg/jsign/files/14720217/pefile_output.txt)

**Comment by ebourg** [comment]
How was the file generated?

**Comment by isagargit** [comment]
using this script:
import pefile

with open("C:\\Users\\<<username>>\\Downloads\\pefile_output.txt", "w") as f:
    pe = pefile.PE("C:\\Users\\<<username>>r\\Downloads\\testapp.exe")
    f.write(pe.dump_info())

**Comment by ebourg** [comment]
Sorry, I meant how was the .exe generated.

**Comment by ebourg** [comment]
What are the bytes at the offsets 0xF2 and 0xF3? That's just after "PE" and should be 0.

**Comment by ebourg** [comment]
@isagargit If you are still around I'd like to figure out why Jsign fails with your file

**Comment by ebourg** [comment]
When Jsign parses an executable file it checks:
- if the file exists and is indeed a file
- if the file is less than 4GB
- if the first two bytes are `MZ`
- if the 4 bytes at the address specified at the offset 0x3C are "PE\0\0"

If any of these tests fail, the unsupported file error is displayed.

I wondered if the PE header verification was too strict, so I've modified a file and set non-zero values after the "PE" bytes. The file became invalid, Windows refused to run it and displayed a big warning message. So Jsign is right to check the two zeros.

I also tried to parse all the PE files under the C:\Windows directory and couldn't find any file triggering the same error.

At this point I fail to see what causes your file to be rejected.

Maybe this is related to something done by the GaraSign CLI? To verify that you could try signing directly with Jsign, using the recently added `--storetype GARASIGN` parameter.

**Comment by nedtwigg** [comment]
fwiw, I bumped into this error today. I narrowed it down to this:

- i had an exe which jsign (and signtool) could sign successfully
- i used resource hacker to alter the icon, but now jsign (and signtool) cannot sign
- i used resource tuner to make the exact same icon alteration, and jsign (and signtool) can sign successfully

I've had lots of luck with resource hacker in general, even with this exact same icon file, seems there is some bug path triggered by the base exe... Bottomline I think jsign's behavior here is correct.

**Comment by ebourg** [comment]
I tried replacing the icon from wineyes.exe with Resource Hacker but Jsign still managed to sign it.

@nedtwigg  Could you send a file modified by resource hacker that couldn't be signed to ebourg@apache.org please? I'll give it a look.

**Comment by ebourg** [comment]
@nedtwigg Thank you for the sample files. I tried signing the modified file and got this error:

```
Adding Authenticode signature to gsudo_with_icon_resource_hacker.exe
java.io.IOException: Invalid certificate table size: -3698331
        at net.jsign.pe.CertificateTableEntry.<init>(CertificateTableEntry.java:46)
        at net.jsign.pe.PEFile.getCertificateTable(PEFile.java:331)
        at net.jsign.pe.PEFile.getSignatures(PEFile.java:299)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:373)
        at net.jsign.SignerHelper.sign(SignerHelper.java:454)
        at net.jsign.SignerHelper.execute(SignerHelper.java:305)
        at net.jsign.JsignCLI.execute(JsignCLI.java:221)
        at net.jsign.JsignCLI.main(JsignCLI.java:57)
jsign: Couldn't sign gsudo_with_icon_resource_hacker.exe
java.io.IOException: The certificate table isn't at the end of the file
        at net.jsign.pe.PEFile.writeCertificateTable(PEFile.java:289)
        at net.jsign.pe.PEFile.setSignature(PEFile.java:312)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:380)
        at net.jsign.SignerHelper.sign(SignerHelper.java:454)
        at net.jsign.SignerHelper.execute(SignerHelper.java:305)
        at net.jsign.JsignCLI.execute(JsignCLI.java:221)
        at net.jsign.JsignCLI.main(JsignCLI.java:57)
```

The original file is actually signed, and it looks like Resource Hacker overwrote the certificate table but didn't update the file header accordingly. So when the file is signed again, Jsign attempts to load the certificate table and fails. Strictly speaking the file is corrupted.

On the other hand, Resource Tuner properly moves the certificate table, the file is still signed after the icon change, but obviously the signature is invalid.

The right approach would be to modify the icon before signing the file.

**Comment by nedtwigg** [comment]
Aha! The `exe` must come presigned in the download, I didn't realize it was getting two different signatures. The other times I've used this flow are unsigned downloads, that's probably the trigger.
