### ISSUE TITLE
Support for Oracle OCI Vault

### ISSUE THREAD

**Issue by Edzilla2000** [ebourg/jsign#213]
Hi, I'm looking at using Oracle OCI Vault HSM with jsign but I don't believe it's supported yet.
The service is free up to 10 keys so I believe it could be a great option.

**Comment by ebourg** [comment]
Yes OCI Vault is on my radar, I haven't got the time to investigate further though. Contributions are welcome :)

**Comment by Edzilla2000** [comment]
@ebourg unfortunately I'm not a developer, but if someone works on it I can definitely do tests

**Comment by ebourg** [comment]
@Edzilla2000 Oracle Cloud support is now implemented, could you give it a try please? There is a snapshot build available here: https://github.com/ebourg/jsign/actions/runs/8455078861/artifacts/1363719072

**Comment by Edzilla2000** [comment]
Of course @ebourg . That was... fast, thanks!

**Comment by Edzilla2000** [comment]
@ebourg I just tried it, this is what I get: 

```
 java -jar jsign-6.1-SNAPSHOT.jar --storetype ORACLECLOUD --alias ocid1.key.oc1.ca-montreal-1.abcdejfhdsf.fdslkfqhksdfjhsqdgfkjqsdfgjkqsdfjkq --certfile domain.crt putty.exe
Adding Authenticode signature to putty.exe
Exception in thread "main" java.lang.NoClassDefFoundError: net/jsign/bouncycastle/pqc/jcajce/provider/sphincsplus/SPHINCSPlusKeyFactorySpi
        at net.jsign.bouncycastle.jce.provider.BouncyCastleProvider.loadPQCKeys(Unknown Source)
        at net.jsign.bouncycastle.jce.provider.BouncyCastleProvider.setup(Unknown Source)
        at net.jsign.bouncycastle.jce.provider.BouncyCastleProvider.access$000(Unknown Source)
        at net.jsign.bouncycastle.jce.provider.BouncyCastleProvider$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.jsign.bouncycastle.jce.provider.BouncyCastleProvider.<init>(Unknown Source)
        at net.jsign.PrivateKeyUtils.readPrivateKeyPEM(PrivateKeyUtils.java:88)
        at net.jsign.PrivateKeyUtils.load(PrivateKeyUtils.java:66)
        at net.jsign.jca.OracleCloudCredentials.getPrivateKey(OracleCloudCredentials.java:74)
        at net.jsign.jca.OracleCloudSigningService.sign(OracleCloudSigningService.java:212)
        at net.jsign.jca.RESTClient.query(RESTClient.java:80)
        at net.jsign.jca.RESTClient.post(RESTClient.java:59)
        at net.jsign.jca.OracleCloudSigningService.sign(OracleCloudSigningService.java:151)
        at net.jsign.jca.SigningServiceSignature.engineSign(SigningServiceSignature.java:46)
        at java.security.Signature$Delegate.engineSign(Unknown Source)
        at java.security.Signature.sign(Unknown Source)
        at net.jsign.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source)
        at net.jsign.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
        at net.jsign.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
        at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.getSignerInfo(AuthenticodeSignedDataGenerator.java:56)
        at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.generate(AuthenticodeSignedDataGenerator.java:43)
        at net.jsign.AuthenticodeSigner.createSignedData(AuthenticodeSigner.java:387)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:362)
        at net.jsign.SignerHelper.sign(SignerHelper.java:396)
        at net.jsign.JsignCLI.execute(JsignCLI.java:135)
        at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.lang.ClassNotFoundException: net.jsign.bouncycastle.pqc.jcajce.provider.sphincsplus.SPHINCSPlusKeyFactorySpi
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 26 more

```		

I'm using jdk8, I will try with a more recent version tomorrow.

**Comment by Edzilla2000** [comment]
@ebourg I get the same result with a more recent version of Java

**Comment by ebourg** [comment]
This is a packaging issue, the unused PQC BouncyCastle classes are removed from the final jar but this breaks the parsing of encrypted key files. This was reported in #163 and I kind of hoped to simply ignore this issue since private key files for signing are deprecated, but here the private key is required for calling the OCI API.

**Comment by ebourg** [comment]
The issue is fixed, here is the snapshot if you want to give it a try: https://github.com/ebourg/jsign/actions/runs/8484299830/artifacts/1370306942

**Comment by Edzilla2000** [comment]
When trying with a private key without a password, it fails because I think the URL you're constructing is not correct: 
It expects "{namespace}-crypto.kms.{region}.oraclecloud.com" and it's using "{namespace}-crypto.kms.{region}.oci.oraclecloud.com"

java -jar jsign-6.1-SNAPSHOT.jar --storetype ORACLECLOUD --alias ocid1.key.oc1.ca-montreal-1.abcde.abcdefghig --certfile domain.crt putty.exe
Adding Authenticode signature to putty.exe
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.OCIJcaProvider <init>
INFO: OCIJCAProvider constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.OCIJcaProvider initialize
INFO: OCIJCAProvider initialize is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.implementation.signature.KeyVaultKeylessRsaSignature <init>
INFO: KeyVaultKeylessRsaSignature Constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.implementation.signature.KeyVaultKeylessRsaSignature <init>
INFO: KeyVaultKeylessRsaSignature Constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.implementation.signature.KeyVaultKeylessEcSignature <init>
INFO: KeyVaultKeylessEcSignature Constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.implementation.signature.KeyVaultKeylessEcSignature <init>
INFO: KeyVaultKeylessEcSignature Constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.implementation.signature.KeyVaultKeylessEcSignature <init>
INFO: KeyVaultKeylessEcSignature Constructor is invoked
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.OCIJcaProvider lambda$0
INFO: OCIJCAProvider initialize is complete
Apr 04, 2024 10:44:12 AM com.oci.security.keyvault.jca.OCIJcaProvider <init>
INFO: OCIJCAProvider constructor is completed
jsign: Couldn't sign putty.exe
net.jsign.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: java.security.GeneralSecurityException: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com
        at net.jsign.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source)
        at net.jsign.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
        at net.jsign.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
        at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.getSignerInfo(AuthenticodeSignedDataGenerator.java:56)
        at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.generate(AuthenticodeSignedDataGenerator.java:43)
        at net.jsign.AuthenticodeSigner.createSignedData(AuthenticodeSigner.java:387)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:362)
        at net.jsign.SignerHelper.sign(SignerHelper.java:396)
        at net.jsign.JsignCLI.execute(JsignCLI.java:135)
        at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.security.SignatureException: java.security.GeneralSecurityException: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com
        at net.jsign.jca.SigningServiceSignature.engineSign(SigningServiceSignature.java:48)
        at java.security.Signature$Delegate.engineSign(Signature.java:1210)
        at java.security.Signature.sign(Signature.java:582)
        ... 10 more
Caused by: java.security.GeneralSecurityException: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com
        at net.jsign.jca.OracleCloudSigningService.sign(OracleCloudSigningService.java:159)
        at net.jsign.jca.SigningServiceSignature.engineSign(SigningServiceSignature.java:46)
        ... 12 more
Caused by: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
        at net.jsign.jca.RESTClient.query(RESTClient.java:88)
        at net.jsign.jca.RESTClient.post(RESTClient.java:59)
        at net.jsign.jca.OracleCloudSigningService.sign(OracleCloudSigningService.java:155)
        ... 13 more
Try `java -jar jsign.jar --help' for more information.

**Comment by Edzilla2000** [comment]
If I add the host to the hosts file, I get this error.

```
jsign: Couldn't sign putty.exe
java.security.SignatureException: Signature verification failed, the private key doesn't match the certificate
        at net.jsign.AuthenticodeSigner.verify(AuthenticodeSigner.java:502)
        at net.jsign.AuthenticodeSigner.createSignedData(AuthenticodeSigner.java:390)
        at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:362)
        at net.jsign.SignerHelper.sign(SignerHelper.java:396)
        at net.jsign.JsignCLI.execute(JsignCLI.java:135)
        at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.security.SignatureException: Signature length not correct: got 512 but was expecting 256
        at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:189)
        at java.security.Signature$Delegate.engineVerify(Signature.java:1222)
        at java.security.Signature.verify(Signature.java:655)
        at net.jsign.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder$SigVerifier.verify(Unknown Source)
        at net.jsign.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder$RawSigVerifier.verify(Unknown Source)
        at net.jsign.bouncycastle.cms.SignerInformation.doVerify(Unknown Source)
        at net.jsign.bouncycastle.cms.SignerInformation.verify(Unknown Source)
        at net.jsign.bouncycastle.cms.CMSSignedData.verifySignatures(Unknown Source)
        at net.jsign.AuthenticodeSigner.verify(AuthenticodeSigner.java:493)
        ... 5 more
```

This might be because I'm using a self signed certificate, as we've not yet gone ahead and bought a code signing certificate since we're still evaluating the process.
But it works when I follow this documentation: https://www.ateam-oracle.com/post/oci-jca-provider-use-case-signing-jar-files

**Comment by ebourg** [comment]
> When trying with a private key that requires a password, it fails because it's not able to get the password from the command line:
Caused by: java.lang.IllegalArgumentException: password empty at net.jsign.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$BasePBKDF2.engineGenerateSecret(Unknown Source) at java.base/

Are you sure the password is specified in the `.oci/config` file ? It looks like the password is missing or empty.

**Comment by Edzilla2000** [comment]
> > When trying with a private key that requires a password, it fails because it's not able to get the password from the command line:
> > Caused by: java.lang.IllegalArgumentException: password empty at net.jsign.bouncycastle.jcajce.provider.symmetric.PBEPBKDF2$BasePBKDF2.engineGenerateSecret(Unknown Source) at java.base/
> 
> Are you sure the password is specified in the `.oci/config` file ? It looks like the password is missing or empty.

It's not, I used the "--keypass" argument. I'd rather not put it in a file but if I have to it's not such an issue

**Comment by ebourg** [comment]
I see, `--keypass` is not used by this keystore type, I'll think about it.

Alternatively you can set the `OCI_CLI_PASS_PHRASE` environment variable if you don't want to store the password in a file.

**Comment by Edzilla2000** [comment]
That's perfect, thanks.

**Comment by ebourg** [comment]
> When trying with a private key without a password, it fails because I think the URL you're constructing is not correct: It expects "{namespace}-crypto.kms.{region}.oraclecloud.com" and it's using "{namespace}-crypto.kms.{region}.oci.oraclecloud.com"
> 
> Caused by: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com

Very interesting, I've created a test key in the eu-paris-1 region and the endpoint was under the oci.oraclecloud.com domain. I wonder if all keys for a given region use the same domain. In this case I could use a static mapping. If not I have to fetch the vault properties before signing.

**Comment by Edzilla2000** [comment]
> > When trying with a private key without a password, it fails because I think the URL you're constructing is not correct: It expects "{namespace}-crypto.kms.{region}.oraclecloud.com" and it's using "{namespace}-crypto.kms.{region}.oci.oraclecloud.com"
> > Caused by: java.net.UnknownHostException: abcde-crypto.kms.ca-montreal-1.oci.oraclecloud.com
> 
> Very interesting, I've created a test key in the eu-paris-1 region and the endpoint was under the oci.oraclecloud.com domain. I wonder if all keys for a given region use the same domain. In this case I could use a static mapping. If not I have to fetch the vault properties before signing.

When looking at the definition it does mention the crypto endpoint, so you probably do have to fetch it from the API:
![image](https://github.com/ebourg/jsign/assets/5339038/9693b548-6cd8-440e-8ff1-a429bd87f3e6)

**Comment by ebourg** [comment]
Yes, but the API uses the management endpoint, which has to be guessed as well. And looking at the OCI console it seems it's also possible to define private endpoints with custom URIs. So this means the management endpoint has to be an input parameter of the signing process.

I have to map the parameters differently, `--keystore` would specify the management endpoint, and the profile should be concatenated to the `--storepass` parameter.

**Comment by ebourg** [comment]
I've made a few changes:
* the `--keypass` parameter can now be used for the API key password
* Jsign resolves the domain of the crypto endpoint before using it, and checks both oci.oraclecloud.com and oraclecloud.com domains
* the configuration profile is now appended to the `--storepass` parameter, this frees the `--keystore` parameter for setting a custom management URL in the future

Let me know how it works for you.
