### ISSUE TITLE
Signing exe with Yubikey on MacOS

### ISSUE THREAD

**Issue by perry-mitchell** [ebourg/jsign#231]
Hello! Thanks for providing jsign - it's exactly what I'm looking for. Though I'm having some issues getting it to sign a local executable:

```
$ jsign --storetype YUBIKEY --storepass 000000 --alias "X.509 Certificate for PIV Authentication" ./my-program.exe

jsign: Failed to load the keystore
java.security.KeyStoreException: Unable to load the keystore null
	at net.jsign.KeyStoreType.getKeystore(KeyStoreType.java:499)
	at net.jsign.KeyStoreBuilder.build(KeyStoreBuilder.java:281)
	at net.jsign.SignerHelper.build(SignerHelper.java:256)
	at net.jsign.SignerHelper.sign(SignerHelper.java:388)
	at net.jsign.JsignCLI.execute(JsignCLI.java:134)
	at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.io.IOException: load failed
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:767)
	at java.base/java.security.KeyStore.load(KeyStore.java:1473)
	at net.jsign.KeyStoreType.getKeystore(KeyStoreType.java:496)
	... 5 more
Caused by: javax.security.auth.login.LoginException
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1512)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.login(P11KeyStore.java:867)
	at jdk.crypto.cryptoki/sun.security.pkcs11.P11KeyStore.engineLoad(P11KeyStore.java:754)
	... 7 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_PIN_LOCKED
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11.C_Login(Native Method)
	at jdk.crypto.cryptoki/sun.security.pkcs11.wrapper.PKCS11$SynchronizedPKCS11.C_Login(PKCS11.java:1687)
	at jdk.crypto.cryptoki/sun.security.pkcs11.SunPKCS11.login(SunPKCS11.java:1496)
	... 9 more
Try `jsign --help' for more information.
```

I have a feeling I'm doing something incorrectly that should be obvious, but I haven't found any info regarding the keystore null issue.

I've installed jsign 6.0 from homebrew, running against my YubiKey 5C NFC FIPS on MacOS Sonoma 14.5.

**Comment by perry-mitchell** [comment]
It was indeed user error - my Yubikey's pin was blocked. Unblocking it fixed this issue.

**Comment by ebourg** [comment]
The keystore null error message is wrong, I'll fix that.

Note that you can also use the `PIV` storetype instead of `YUBIKEY`, it's slightly easier to use as it doesn't require libykcs11 to be installed.

**Comment by perry-mitchell** [comment]
I tried the PIV type and it failed, some long complex error. If I find the trace I'll attach it here.

But thanks! It ultimately worked perfectly and I'm back on track with code signing and didn't have to leave the confort of my OS.

**Comment by perry-mitchell** [comment]
@ebourg This is what I got using the PIV type:

```
$ jsign --storetype PIV --storepass 000000 --alias "X.509 Certificate for PIV Authentication" ./my-program.exe
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/jsign/jca/PIVCardSigningService.sign(Lnet/jsign/jca/SigningServicePrivateKey;Ljava/lang/String;[B)[B @156: invokespecial
  Reason:
    Type 'java/lang/Object' (current frame, stack[2]) is not assignable to 'java/lang/Throwable'
  Current Frame:
    bci: @156
    flags: { }
    locals: { top, top, top, top, top, top, top, 'java/lang/Object' }
    stack: { uninitialized 150, uninitialized 150, 'java/lang/Object' }
  Bytecode:
    0000000: 2c03 2cb6 0038 1206 b600 36b6 0037 b800
    0000010: 4a3a 0419 04b6 0049 2db6 003f 3a05 2bb6
    0000020: 0057 b800 543a 062a b400 3119 06b6 0051
    0000030: 3a07 1204 2bb6 0056 b600 3599 0029 bb00
    0000040: 2759 bb00 2659 1904 b400 2eb2 002f b700
    0000050: 4b19 05b7 004c 3a09 1909 1201 b600 4d3a
    0000060: 08a7 0027 1905 be19 07b4 0030 1008 6ca4
    0000070: 0015 1905 1907 b400 3010 086c b800 443a
    0000080: 08a7 0007 1905 3a08 2ab4 0031 1906 1908
    0000090: b600 52b0 3a07 bb00 1259 1907 b700 3dbf
    00000a0:
  Exception Handler Table:
    bci [39, 147] => handler: 148
    bci [39, 147] => handler: 148
  Stackmap Table:
    full_frame(@100,{Object[#43],Top,Top,Top,Top,Object[#7],Object[#41],Object[#42]},{})
    chop_frame(@132,1)
    full_frame(@136,{Object[#43],Top,Top,Top,Top,Top,Object[#41],Top,Object[#7]},{})
    full_frame(@148,{},{Object[#12]})

	at net.jsign.KeyStoreType$8.getProvider(KeyStoreType.java:224)
	at net.jsign.KeyStoreBuilder.provider(KeyStoreBuilder.java:268)
	at net.jsign.KeyStoreBuilder.build(KeyStoreBuilder.java:281)
	at net.jsign.SignerHelper.build(SignerHelper.java:256)
	at net.jsign.SignerHelper.sign(SignerHelper.java:388)
	at net.jsign.JsignCLI.execute(JsignCLI.java:134)
	at net.jsign.JsignCLI.main(JsignCLI.java:40)
```

**Comment by ebourg** [comment]
Ah yes, that was fixed recently. You can use the latest snapshot build if you want to try (https://github.com/ebourg/jsign/actions/runs/9797077297/artifacts/1668701812).
