### ISSUE TITLE
error after 30 minutes : "SCARD_E_NO_SERVICE"

### ISSUE THREAD

**Issue by nauni77** [ebourg/jsign#233]
Hello, I used jsign to write a little service for signing our code. But using "PIV" I got an error after approximate 30 minutes. This happened more than one time. Can you help?

Best regards, Oli

The stacktrace of the error:
```bash
2024-07-05T12:39:27.677+02:00 ERROR 67514 --- [codeSignService] [   scheduling-1] d.n.c.scheduled.CodeSignScheduler        : failed to sign file: FileDTO(fileUUID=f2132328-95db-4fcd-9eab-4a969cad0fa3, uploadedDate=Fri Jul 05 12:39:27 CEST 2024, signStartDate=Fri Jul 05 12:39:27 CEST 2024, signEndDate=null, downloadedDate=null, signed=false, signError=true, signErrorException=de.company.codesignservice.exceptions.CodeSigningException: something went wrong during signing the file, downloaded=false, originalFileName=HelloWorld.exe, uploadFileSize=321456)

de.company.codesignservice.exceptions.CodeSigningException: something went wrong during signing the file
	at de.company.codesignservice.signing.CodeSigningWithAPI.signFile(CodeSigningWithAPI.java:89) ~[main/:na]
	at de.company.codesignservice.signing.CodeSigningBean.signFile(CodeSigningBean.java:36) ~[main/:na]
	at de.company.codesignservice.scheduled.CodeSignScheduler.scheduledSigning(CodeSignScheduler.java:39) ~[main/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.runInternal(ScheduledMethodRunnable.java:130) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.lambda$run$2(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.10.jar:6.1.10]
	at io.micrometer.observation.Observation.observe(Observation.java:499) ~[micrometer-observation-1.13.1.jar:1.13.1]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:124) ~[spring-context-6.1.10.jar:6.1.10]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.1.10.jar:6.1.10]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
Caused by: org.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: java.security.GeneralSecurityException: javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: SCARD_E_NO_SERVICE
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source) ~[bcpkix-lts8on-2.73.6.jar:na]
	at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source) ~[bcpkix-lts8on-2.73.6.jar:na]
	at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source) ~[bcpkix-lts8on-2.73.6.jar:na]
	at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.getSignerInfo(AuthenticodeSignedDataGenerator.java:56) ~[jsign-core-7.0-SNAPSHOT.jar:na]
	at net.jsign.asn1.authenticode.AuthenticodeSignedDataGenerator.generate(AuthenticodeSignedDataGenerator.java:43) ~[jsign-core-7.0-SNAPSHOT.jar:na]
	at net.jsign.AuthenticodeSigner.createSignedData(AuthenticodeSigner.java:395) ~[jsign-core-7.0-SNAPSHOT.jar:na]
	at net.jsign.AuthenticodeSigner.sign(AuthenticodeSigner.java:370) ~[jsign-core-7.0-SNAPSHOT.jar:na]
	at de.company.codesignservice.signing.CodeSigningWithAPI.signFile(CodeSigningWithAPI.java:86) ~[main/:na]
	... 16 common frames omitted
Caused by: java.security.SignatureException: java.security.GeneralSecurityException: javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: SCARD_E_NO_SERVICE
	at net.jsign.jca.SigningServiceSignature.engineSign(SigningServiceSignature.java:48) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1423) ~[na:na]
	at java.base/java.security.Signature.sign(Signature.java:712) ~[na:na]
	... 24 common frames omitted
Caused by: java.security.GeneralSecurityException: javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: SCARD_E_NO_SERVICE
	at net.jsign.jca.PIVCardSigningService.sign(PIVCardSigningService.java:149) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	at net.jsign.jca.SigningServiceSignature.engineSign(SigningServiceSignature.java:46) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	... 26 common frames omitted
Caused by: javax.smartcardio.CardException: sun.security.smartcardio.PCSCException: SCARD_E_NO_SERVICE
	at java.smartcardio/sun.security.smartcardio.ChannelImpl.doTransmit(ChannelImpl.java:226) ~[java.smartcardio:na]
	at java.smartcardio/sun.security.smartcardio.ChannelImpl.transmit(ChannelImpl.java:89) ~[java.smartcardio:na]
	at net.jsign.jca.SmartCard.transmit(SmartCard.java:79) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	at net.jsign.jca.PIVCard.verify(PIVCard.java:168) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	at net.jsign.jca.PIVCard.sign(PIVCard.java:326) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	at net.jsign.jca.PIVCardSigningService.sign(PIVCardSigningService.java:147) ~[jsign-crypto-7.0-SNAPSHOT.jar:na]
	... 27 common frames omitted
Caused by: sun.security.smartcardio.PCSCException: SCARD_E_NO_SERVICE
	at java.smartcardio/sun.security.smartcardio.PCSC.SCardTransmit(Native Method) ~[java.smartcardio:na]
	at java.smartcardio/sun.security.smartcardio.ChannelImpl.doTransmit(ChannelImpl.java:192) ~[java.smartcardio:na]
	... 32 common frames omitted

2024-07-05T12:39:29.302+02:00  INFO 67514 --- [codeSignService] [   scheduling-1] d.n.c.scheduled.CodeSignScheduler        : unsigned queue size: 0
```

**Comment by ebourg** [comment]
That's still with a Yubikey right? I haven't tested long lived session, I'll give it a try.

**Comment by nauni77** [comment]
Hi, yes it's Yubikey - right! But I used PIV for signing.

**Comment by ebourg** [comment]
Do you know if the Yubikey was idle for 30 minutes?

**Comment by ebourg** [comment]
I tried keeping an active session for 1 hour with signatures every 15 seconds, and idle for 35 minutes before signing, it worked in both cases (on Windows 10).

However I noticed that unplugging/plugging the Yubikey while idle caused an unrecoverable SCARD_E_READER_UNAVAILABLE error.

Keeping the `javax.smartcardio.CardChannel` open for a long time is probably not a good idea. I'll check if closing/reopening it when needed doesn't impact the performance.

In the meantime I think you can work around this issue by creating a new keystore every time you want to sign.

**Comment by nauni77** [comment]
I think closing the CardChannel after using it and open it again as soon you need it again will be a good approach.

However, this happened often to me and I'm not sure why it's now working (without changing it like you described above - creating a new keystore for every use). But I will change it and create a new KeyStore for every signing - I will also check if the signing takes longer doing it this way. I will report it here.

The next days I will have an eye on this topic and will write a message if the exception `"SCARD_E_NO_SERVICE"` happens again.

**Comment by ebourg** [comment]
I've also seen a SCARD_W_RESET_CARD error if another application uses the Yubikey.

**Comment by nauni77** [comment]
Hello, I tried it now quite often and the issue is gone. 

Maybe you're right and the open "YubiKey manager" sometimes accessed the YubiKey - may this caused the error.

Anyway, thanks a lot for your help! I will close this issue.

Best regards, Oli
