### ISSUE TITLE
Azure TRUSTEDSIGNING (ClaimsPrincipal TenantId is null)

### ISSUE THREAD

**Issue by vtl-btz** [ebourg/jsign#243]
```
User-Agent: Jsign (https://ebourg.github.io/jsign/)
Content-Type: application/json; charset=utf-8
Content:
{"digest":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","signatureAlgorithm":"RS256"}
Response Code: 500
Content-Type: application/json
Error:
{"errorDetail":{"code":"InternalError","message":"ClaimsPrincipal TenantId is null.","target":null}}
jsign: Unable to retrieve the certificate chain 'signAccName/certName'
java.security.KeyStoreException: Unable to retrieve the certificate chain 'signAccName/certName'
        at net.jsign.jca.AzureTrustedSigningService.getCertificateChain(AzureTrustedSigningService.java:109)
        at net.jsign.jca.SigningServiceKeyStore.engineGetCertificateChain(SigningServiceKeyStore.java:43)
        at java.base/java.security.KeyStore.getCertificateChain(Unknown Source)
        at net.jsign.SignerHelper.build(SignerHelper.java:359)
        at net.jsign.SignerHelper.sign(SignerHelper.java:471)
        at net.jsign.SignerHelper.execute(SignerHelper.java:310)
        at net.jsign.JsignCLI.execute(JsignCLI.java:211)
        at net.jsign.JsignCLI.main(JsignCLI.java:57)
Caused by: java.io.IOException: InternalError - ClaimsPrincipal TenantId is null.
        at net.jsign.jca.RESTClient.query(RESTClient.java:159)
        at net.jsign.jca.RESTClient.post(RESTClient.java:73)
        at net.jsign.jca.AzureTrustedSigningService.sign(AzureTrustedSigningService.java:147)
        at net.jsign.jca.AzureTrustedSigningService.getCertificateChain(AzureTrustedSigningService.java:106)
        ... 7 more
```

I have downloaded the last build from Actions [here](https://github.com/ebourg/jsign/actions/runs/10063296846)

to get an access token I use:
```
az account get-access-token --subscription $subscriptionId
```

running with command 
```
java -jar ./jsign-7.0-SNAPSHOT.jar --storetype TRUSTEDSIGNING --keystore $rootUrl --storepass $token --alias $signingAccount/$signingProfile $filePath --debug
```

not working on archlinux and windows
```
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7)
OpenJDK 64-Bit Server VM (build 17.0.12+7, mixed mode, sharing)
```

**Comment by ebourg** [comment]
Did you try setting the resource when fetching the access token?

    az account get-access-token --resource https://codesigning.azure.net

**Comment by ebourg** [comment]
If it doesn't work with the resource, could you decode the token on https://jwt.io and check if the `tid` field is not null?

**Comment by vtl-btz** [comment]
Thank you! It works!
