### ISSUE TITLE
PKCS11 configuration files can only be loaded from the current directory

### ISSUE THREAD

**Issue by s3zwirni** [ebourg/jsign#39]
Hi,

i try to run a ant-build with my certum-token to sign a exe-file and get the following error:

Error parsing configuration

XML is valide, the responsible part:

```
<taskdef name="signexe" classname="net.jsign.PESignerTask" classpath="build/lib/jsign-2.0.jar"/>
  	
  	<signexe file="installer/accessRights/S3AccessRights.exe"
  	  			name="aLobby"
  	  			url="https://alobby.siedler3.net"
  		        keystore="installer/signingCert/project.cfg"
  		        storetype="PKCS11"
  		        alg="SHA-256"
  		        alias="Open Source Developer, Thomas Zwirner"
  		        storepass="password"
  		        tsaurl="http://time.certum.pl"/>
```
First i check if the path must be written with \ instead of / - no luck.

The project.cfg:

```
name=Crypto3CSP
library=C:\Windows\System32\crypto3PKCS.dll
slot=-1
```
Same configuration and project.cfg runs with no problems with jarsigner to sign a jar-file.

What am i missing?

**Comment by ebourg** [comment]
Hi, do you get a stacktrace with the error message? Are you able to use the token with other Java applications (with jarsigner for example).

**Comment by s3zwirni** [comment]
Same configuration and project.cfg runs with no problems with jarsigner to sign a jar-file.

I got no stacktrace of this error - only this line :(

**Comment by ebourg** [comment]
What is your command line with jarsigner?

**Comment by ebourg** [comment]
Do you see a stacktrace if you run ant with the `-debug` and the `-verbose` options?

**Comment by s3zwirni** [comment]
**jarsigner:**

```
<exec executable="jarsigner.exe">
      <arg line="-keystore NONE -tsa 'http://time.certum.pl' -storetype PKCS11 -providerClass sun.security.pkcs11.SunPKCS11 -providerArg 'installer/signingCert/project.cfg' -storepass 'password' 'release/alobby.jar' 'Open Source Developer, Thomas Zwirner'"/>
    </exec>
```
**stacktrace:**
```
build.xml:371: Error parsing configuration
	at net.jsign.PESignerTask.execute(PESignerTask.java:167)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:453)
	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:140)
Caused by: java.security.ProviderException: Error parsing configuration
	at sun.security.pkcs11.Config.getConfig(Config.java:88)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:129)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	at net.jsign.PESignerHelper.build(PESignerHelper.java:258)
	at net.jsign.PESignerHelper.sign(PESignerHelper.java:353)
	at net.jsign.PESignerTask.execute(PESignerTask.java:165)
	... 15 more
Caused by: java.io.FileNotFoundException: project.cfg (Das System kann die angegebene Datei nicht finden)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.security.pkcs11.Config.<init>(Config.java:211)
	at sun.security.pkcs11.Config.getConfig(Config.java:84)
	... 20 more
```
Seems like he can't find project.cfg which results in another error-message ..

**Comment by ebourg** [comment]
Does it work better if you copy the project.cfg file to the current directory?

**Comment by s3zwirni** [comment]
If i copy it into the same directory as build.xml and change keystore-attribute to 

keystore="build/project.cfg"

it works :-) But why not if the file locates in another directory?

**Comment by ebourg** [comment]
Ok, so it looks like the path is ignored. That's odd, because I did fix an issue like this one back in January (89a4055).

**Comment by s3zwirni** [comment]
Let me know if i might help you test it for you.

**Comment by ebourg** [comment]
Ok understood. I fixed the wrong line, the `keystore.getName()` that should have been changed into `keystore.getPath()` is the one two lines above:

https://github.com/ebourg/jsign/blob/master/jsign-core/src/main/java/net/jsign/PESignerHelper.java#L258

**Comment by s3zwirni** [comment]
Tries to compile the jsign-2.0.jar with actual sources from github _before_ changing the file you described with following command:

`mvn package`

but this results in:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.11:test (default-test) on project jsign-cli: There are test failures.
[ERROR]
[ERROR] Please refer to E:\workspace\jsign\jsign-cli\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
```
In this directory i found:
```
-------------------------------------------------------------------------------
Test set: net.jsign.PESignerCLITest
-------------------------------------------------------------------------------
Tests run: 34, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 13.792 sec <<< FAILURE!
testBrokenPKCS11Configuration(net.jsign.PESignerCLITest)  Time elapsed: 0.18 sec  <<< ERROR!
net.jsign.SignerException: Couldn't sign target\test-classes\wineyes-signed-with-cli.exe
	at net.jsign.PESignerHelper.sign(PESignerHelper.java:359)
	at net.jsign.PESignerCLI.execute(PESignerCLI.java:109)
	at net.jsign.PESignerCLITest.testBrokenPKCS11Configuration(PESignerCLITest.java:513)
Caused by: java.security.ProviderException: Error parsing configuration
	at sun.security.pkcs11.Config.getConfig(Config.java:88)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:129)
	at sun.security.pkcs11.SunPKCS11.<init>(SunPKCS11.java:103)
	at net.jsign.PESignerHelper.build(PESignerHelper.java:258)
	at net.jsign.PESignerHelper.sign(PESignerHelper.java:355)
	... 30 more
Caused by: sun.security.pkcs11.ConfigurationException: Unexpected token: Token['<'], line 1
	at sun.security.pkcs11.Config.excToken(Config.java:375)
	at sun.security.pkcs11.Config.parse(Config.java:392)
	at sun.security.pkcs11.Config.<init>(Config.java:220)
	at sun.security.pkcs11.Config.getConfig(Config.java:84)
	... 34 more
```

How can i compile it to test this change you described?

**Comment by ebourg** [comment]
Just skip the tests with:

    mvn package -DskipTests

**Comment by s3zwirni** [comment]
Compiled now with:

`mvn package -DskipTests -Dmaven.javadoc.skip=true`

And your fix worked perfectly for me :)

**Comment by ebourg** [comment]
@s3zwirni I applied the fix as well as a modification to make this part of the code compatible with Java 9. If you have the opportunity to test with Java 9 I'd be interested in your feedback.
