### ISSUE TITLE
Couldn't open the executable file with gradle and relative path

### ISSUE THREAD

**Issue by rchovan** [ebourg/jsign#61]
Hi, 
when gradle and relative path is used for parameter file, application is not signed.
OS: Windows 10 64bit
gradle: 5.6.2

```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\radoslav.chovan\Projects\Samples\HelloWorld\build.gradle' line: 58

* What went wrong:
A problem occurred evaluating root project 'HelloWorld'.
> Couldn't open the executable file build\launch4j\hello_world.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

sign does not work when file is used like this:
```
file      : 'build/launch4j/hello_world.exe'
file      : '${projectDir}/build/launch4j/hello_world.exe'
file      : 'build\\launch4j\\hello_world.exe'
```

sign work only with full path:
```
file      : 'C:\\Users\\radoslav.chovan\\Projects\\Samples\\HelloWorld\\build\\launch4j\\hello_world.exe'
```
```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>gradle build

BUILD SUCCESSFUL in 1s
6 actionable tasks: 1 executed, 5 up-to-date
```

Here is my template project, which you can use and test:  https://github.com/rchovan/poc_jsign

**Comment by ebourg** [comment]
Do you get an exception if you run gradle with --stacktrace ?

**Comment by rchovan** [comment]
Yes, details are here > https://scans.gradle.com/s/3nta35qy3v7s6

**Comment by ebourg** [comment]
It looks like the file doesn't exist:

```
  java.nio.file.NoSuchFileException: build\launch4j\hello_world.exe
          at net.jsign.pe.PEFile.<init>(PEFile.java:79)
          at net.jsign.PESignerHelper.sign(PESignerHelper.java:393)
          at net.jsign.PESignerGradlePlugin$1.doCall(PESignerGradlePlugin.java:45)
```

**Comment by rchovan** [comment]
the file exist, you can try example project which I mentioned in 1st post. 

```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>dir build\launch4j\
 Volume in drive C is OS
 Volume Serial Number is 0CF7-D967

 Directory of C:\Users\radoslav.chovan\Projects\Samples\HelloWorld\build\launch4j

08. 10. 2019  09:10    <DIR>          .
08. 10. 2019  09:10    <DIR>          ..
08. 10. 2019  09:10            26 813 hello_world.exe
08. 10. 2019  09:10    <DIR>          lib
               1 File(s)         26 813 bytes
               3 Dir(s)  18 045 726 720 bytes free

```

**Comment by ebourg** [comment]
Are the tasks parallelized?

**Comment by rchovan** [comment]
Hi @ebourg , are you able to reproduce this issue ?

**Comment by ebourg** [comment]
Sorry I don't have the time to check right now. Maybe you could print the content of the build directory in the Gradle script just before jsign is invoked?

**Comment by ebourg** [comment]
Looking at your Gradle script, I think you forgot to wrap the jsign invocation in a `doLast` block. So Jsign runs at configuration time before the executable is built by launch4j.

**Comment by ebourg** [comment]
The right syntax is:

    task sign {
        doLast {
            signexe(file      : 'build/launch4j/hello_world.exe',
                    name      : 'hello_world',
                    url       : 'https://company.com/product',
                    keystore  : 'helloworld.pfx',
                    storetype : 'PKCS12',
                    alias     : 'helloworld',
                    storepass : 'storepass',
                    keypass   : 'keypass',
                    tsaurl    : 'http://timestamp.comodoca.com/authenticode')
        }
    }

**Comment by rchovan** [comment]
Hi, 
code updated with doLast, but still can't get it working: 

```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>gradle build

BUILD SUCCESSFUL in 1s
6 actionable tasks: 6 up-to-date

```
gradle build finished without error

check if file exist
```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>dir build\launch4j\
 Volume in drive C is OS
 Volume Serial Number is 0CF7-D967

 Directory of C:\Users\radoslav.chovan\Projects\Samples\HelloWorld\build\launch4j

20. 12. 2019  09:52    <DIR>          .
20. 12. 2019  09:52    <DIR>          ..
20. 12. 2019  09:52            26 813 hello_world.exe
20. 12. 2019  09:51    <DIR>          lib
               1 File(s)         26 813 bytes
               3 Dir(s)  159 536 197 632 bytes free
```
file exist, running gradle sign

```
C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>gradle sign
> Task :sign FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\radoslav.chovan\Projects\Samples\HelloWorld\build.gradle' line: 59

* What went wrong:
Execution failed for task ':sign'.
> net.jsign.SignerException: Couldn't open the executable file build\launch4j\hello_world.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

C:\Users\radoslav.chovan\Projects\Samples\HelloWorld>

```

gradle sign failed
