### ISSUE TITLE
Unable to sign binaries with GOOGLECLOUD

### ISSUE THREAD

**Issue by rvadim** [ebourg/jsign#91]
**STR:**
1.  Generate asymmetric key and CA
```
gcloud kms keyrings create test --location <region>```
gcloud kms keys create my-key --keyring test --location <region> --purpose "asymmetric-signing" --default-algorithm "rsa-sign-pkcs1-2048-sha256"
openssl genrsa -out ca.key 2048
```
2. Create CSR and Certificate
```
git clone https://github.com/mattes/google-cloud-kms-csr
cd google-cloud-kms-csr
go build -o csr
./csr -key $(gcloud kms keys versions list  --key my-key --keyring test --location=<region>) -out my.csr --common-name MyOrg
openssl -req -in my.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out my.crt
```
3. Run jsign
```
jsign --storetype GOOGLECLOUD
  --storepass "$(gcloud auth print-access-token)"
  --keystore "projects/<project>/locations/<location>/keyRings/test"
  --alias "my-key"
  --certfile my.crt
  my.exe
```

**Expected result:**
Binary signed

**Actual result:**
```
jsign: Couldn't sign my.exe
java.lang.RuntimeException: java.security.KeyStoreException: java.io.IOException: HTTP Error 404 - Not Found
	at net.jsign.jca.SigningServiceKeyStore.engineAliases(SigningServiceKeyStore.java:88)
	at java.base/java.security.KeyStore.aliases(KeyStore.java:1269)
	at net.jsign.SignerHelper.build(SignerHelper.java:338)
	at net.jsign.SignerHelper.sign(SignerHelper.java:476)
	at net.jsign.JsignCLI.execute(JsignCLI.java:113)
	at net.jsign.JsignCLI.main(JsignCLI.java:40)
Caused by: java.security.KeyStoreException: java.io.IOException: HTTP Error 404 - Not Found
	at net.jsign.jca.GoogleCloudSigningService.aliases(GoogleCloudSigningService.java:81)
	at net.jsign.jca.SigningServiceKeyStore.engineAliases(SigningServiceKeyStore.java:86)
	... 5 more
Caused by: java.io.IOException: HTTP Error 404 - Not Found
	at net.jsign.jca.RESTClient.query(RESTClient.java:76)
	at net.jsign.jca.RESTClient.get(RESTClient.java:43)
	at net.jsign.jca.GoogleCloudSigningService.aliases(GoogleCloudSigningService.java:74)
	... 6 more
Try `java -jar jsign.jar --help' for more information.
```

**Comment by ebourg** [comment]
There is another issue with the certfile parameter, I'm looking into it.

**Comment by ebourg** [comment]
This should be fixed now, let me know how it works for you.

**Comment by rvadim** [comment]
> This should be fixed now, let me know how it works for you.
Excellent! Now `--certfile` works even if there are several certificates in the file.

Thank you!

**Comment by ebourg** [comment]
Great! Thank you for the feedback.
